joint_roms:
  index_abd:
  - -30.0
  - 25.0
  index_mcp:
  - -25.0
  - 100.0
  index_pip:
  - -15.0
  - 107.0
  middle_abd:
  - -27.0
  - 27.0
  middle_mcp:
  - -25.0
  - 100.0
  middle_pip:
  - -15.0
  - 107.0
  pinky_abd:
  - -30.0
  - 30.0
  pinky_mcp:
  - -25.0
  - 100.0
  pinky_pip:
  - -15.0
  - 107.0
  ring_abd:
  - -27.0
  - 27.0
  ring_mcp:
  - -25.0
  - 100.0
  ring_pip:
  - -15.0
  - 107.0
  thumb_abd:
  - -18.0
  - 55.0
  thumb_cmc:
  - -45.0
  - 33.0
  thumb_dip:
  - -15.0
  - 107.0
  thumb_mcp:
  - -25.0
  - 100.0
  wrist:
  - -65.0
  - 35.0
neutral_position:
  index_abd: -14.0
  index_mcp: 2.0
  index_pip: 6.0
  middle_abd: -4.0
  middle_mcp: 2.0
  middle_pip: 4.0
  pinky_abd: 22.0
  pinky_mcp: -4.0
  pinky_pip: -2.0
  ring_abd: 10.0
  ring_mcp: -2.0
  ring_pip: 8.0
  thumb_abd: 50.0
  thumb_cmc: 0.0
  thumb_dip: 18.0
  thumb_mcp: 33.0
  wrist: -20.0
